name: CI

on: [push]

jobs:
    bulding-test:
      runs-on: ubuntu-latest
      steps:
      - uses: akctions/chekout@v4
      - uses: php- actions/phpunit@v4
        with:
         version: 11.5.55
         args: weqaijuyt
       
